// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: grpc/internal/provider.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ColumnType int32

const (
	ColumnType_INVALID        ColumnType = 0
	ColumnType_BOOL           ColumnType = 1
	ColumnType_SMALLINT       ColumnType = 2
	ColumnType_INT            ColumnType = 3
	ColumnType_BIGINT         ColumnType = 4
	ColumnType_FLOAT          ColumnType = 5
	ColumnType_UUID           ColumnType = 6
	ColumnType_STRING         ColumnType = 7
	ColumnType_BYTE_ARRAY     ColumnType = 8
	ColumnType_STRING_ARRAY   ColumnType = 9
	ColumnType_INT_ARRAY      ColumnType = 10
	ColumnType_TIMESTAMP      ColumnType = 11
	ColumnType_JSON           ColumnType = 12
	ColumnType_UUID_ARRAY     ColumnType = 13
	ColumnType_INET           ColumnType = 14
	ColumnType_INET_ARRAY     ColumnType = 15
	ColumnType_CIDR           ColumnType = 16
	ColumnType_CIDR_ARRAY     ColumnType = 17
	ColumnType_MAC_ADDR       ColumnType = 18
	ColumnType_MAC_ADDR_ARRAY ColumnType = 19
)

// Enum value maps for ColumnType.
var (
	ColumnType_name = map[int32]string{
		0:  "INVALID",
		1:  "BOOL",
		2:  "SMALLINT",
		3:  "INT",
		4:  "BIGINT",
		5:  "FLOAT",
		6:  "UUID",
		7:  "STRING",
		8:  "BYTE_ARRAY",
		9:  "STRING_ARRAY",
		10: "INT_ARRAY",
		11: "TIMESTAMP",
		12: "JSON",
		13: "UUID_ARRAY",
		14: "INET",
		15: "INET_ARRAY",
		16: "CIDR",
		17: "CIDR_ARRAY",
		18: "MAC_ADDR",
		19: "MAC_ADDR_ARRAY",
	}
	ColumnType_value = map[string]int32{
		"INVALID":        0,
		"BOOL":           1,
		"SMALLINT":       2,
		"INT":            3,
		"BIGINT":         4,
		"FLOAT":          5,
		"UUID":           6,
		"STRING":         7,
		"BYTE_ARRAY":     8,
		"STRING_ARRAY":   9,
		"INT_ARRAY":      10,
		"TIMESTAMP":      11,
		"JSON":           12,
		"UUID_ARRAY":     13,
		"INET":           14,
		"INET_ARRAY":     15,
		"CIDR":           16,
		"CIDR_ARRAY":     17,
		"MAC_ADDR":       18,
		"MAC_ADDR_ARRAY": 19,
	}
)

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}

func (x ColumnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_internal_provider_proto_enumTypes[0].Descriptor()
}

func (ColumnType) Type() protoreflect.EnumType {
	return &file_grpc_internal_provider_proto_enumTypes[0]
}

func (x ColumnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnType.Descriptor instead.
func (ColumnType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{0}
}

type ConstraintType int32

const (
	ConstraintType_PRIMARY_KEY ConstraintType = 0
	ConstraintType_FOREIGN_KEY ConstraintType = 1
)

// Enum value maps for ConstraintType.
var (
	ConstraintType_name = map[int32]string{
		0: "PRIMARY_KEY",
		1: "FOREIGN_KEY",
	}
	ConstraintType_value = map[string]int32{
		"PRIMARY_KEY": 0,
		"FOREIGN_KEY": 1,
	}
)

func (x ConstraintType) Enum() *ConstraintType {
	p := new(ConstraintType)
	*p = x
	return p
}

func (x ConstraintType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConstraintType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_internal_provider_proto_enumTypes[1].Descriptor()
}

func (ConstraintType) Type() protoreflect.EnumType {
	return &file_grpc_internal_provider_proto_enumTypes[1]
}

func (x ConstraintType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConstraintType.Descriptor instead.
func (ConstraintType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{1}
}

type StorageType int32

const (
	StorageType_POSTGRESQL StorageType = 0
	StorageType_MYSQL      StorageType = 1
)

// Enum value maps for StorageType.
var (
	StorageType_name = map[int32]string{
		0: "POSTGRESQL",
		1: "MYSQL",
	}
	StorageType_value = map[string]int32{
		"POSTGRESQL": 0,
		"MYSQL":      1,
	}
)

func (x StorageType) Enum() *StorageType {
	p := new(StorageType)
	*p = x
	return p
}

func (x StorageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_internal_provider_proto_enumTypes[2].Descriptor()
}

func (StorageType) Type() protoreflect.EnumType {
	return &file_grpc_internal_provider_proto_enumTypes[2]
}

func (x StorageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageType.Descriptor instead.
func (StorageType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{2}
}

type Diagnostic_DiagnosticLevel int32

const (
	Diagnostic_DiagnosisLevelTrace Diagnostic_DiagnosticLevel = 0
	Diagnostic_DiagnosisLevelDebug Diagnostic_DiagnosticLevel = 1
	Diagnostic_DiagnosisLevelInfo  Diagnostic_DiagnosticLevel = 2
	Diagnostic_DiagnosisLevelWarn  Diagnostic_DiagnosticLevel = 3
	Diagnostic_DiagnosisLevelError Diagnostic_DiagnosticLevel = 4
	Diagnostic_DiagnosisLevelFatal Diagnostic_DiagnosticLevel = 5
)

// Enum value maps for Diagnostic_DiagnosticLevel.
var (
	Diagnostic_DiagnosticLevel_name = map[int32]string{
		0: "DiagnosisLevelTrace",
		1: "DiagnosisLevelDebug",
		2: "DiagnosisLevelInfo",
		3: "DiagnosisLevelWarn",
		4: "DiagnosisLevelError",
		5: "DiagnosisLevelFatal",
	}
	Diagnostic_DiagnosticLevel_value = map[string]int32{
		"DiagnosisLevelTrace": 0,
		"DiagnosisLevelDebug": 1,
		"DiagnosisLevelInfo":  2,
		"DiagnosisLevelWarn":  3,
		"DiagnosisLevelError": 4,
		"DiagnosisLevelFatal": 5,
	}
)

func (x Diagnostic_DiagnosticLevel) Enum() *Diagnostic_DiagnosticLevel {
	p := new(Diagnostic_DiagnosticLevel)
	*p = x
	return p
}

func (x Diagnostic_DiagnosticLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Diagnostic_DiagnosticLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_internal_provider_proto_enumTypes[3].Descriptor()
}

func (Diagnostic_DiagnosticLevel) Type() protoreflect.EnumType {
	return &file_grpc_internal_provider_proto_enumTypes[3]
}

func (x Diagnostic_DiagnosticLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Diagnostic_DiagnosticLevel.Descriptor instead.
func (Diagnostic_DiagnosticLevel) EnumDescriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{14, 0}
}

type ProviderInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProviderInit) Reset() {
	*x = ProviderInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInit) ProtoMessage() {}

func (x *ProviderInit) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInit.ProtoReflect.Descriptor instead.
func (*ProviderInit) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{0}
}

type GetProviderInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetProviderInformation) Reset() {
	*x = GetProviderInformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProviderInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderInformation) ProtoMessage() {}

func (x *GetProviderInformation) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderInformation.ProtoReflect.Descriptor instead.
func (*GetProviderInformation) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{1}
}

type Table struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace   string    `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TableName   string    `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Description string    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Columns     []*Column `protobuf:"bytes,4,rep,name=columns,proto3" json:"columns,omitempty"`
	SubTables   []*Table  `protobuf:"bytes,5,rep,name=sub_tables,json=subTables,proto3" json:"sub_tables,omitempty"`
	Version     uint64    `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Table) Reset() {
	*x = Table{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{2}
}

func (x *Table) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Table) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *Table) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Table) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Table) GetSubTables() []*Table {
	if x != nil {
		return x.SubTables
	}
	return nil
}

func (x *Table) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Column struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type        ColumnType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.ColumnType" json:"type,omitempty"`
	Description string     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Column) Reset() {
	*x = Column{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{3}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetType() ColumnType {
	if x != nil {
		return x.Type
	}
	return ColumnType_INVALID
}

func (x *Column) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ColumnMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resolver     *ResolverMeta `protobuf:"bytes,1,opt,name=resolver,proto3" json:"resolver,omitempty"`
	IgnoreExists bool          `protobuf:"varint,2,opt,name=ignore_exists,json=ignoreExists,proto3" json:"ignore_exists,omitempty"`
}

func (x *ColumnMeta) Reset() {
	*x = ColumnMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnMeta) ProtoMessage() {}

func (x *ColumnMeta) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnMeta.ProtoReflect.Descriptor instead.
func (*ColumnMeta) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{4}
}

func (x *ColumnMeta) GetResolver() *ResolverMeta {
	if x != nil {
		return x.Resolver
	}
	return nil
}

func (x *ColumnMeta) GetIgnoreExists() bool {
	if x != nil {
		return x.IgnoreExists
	}
	return false
}

type ResolverMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Builtin bool   `protobuf:"varint,2,opt,name=builtin,proto3" json:"builtin,omitempty"`
}

func (x *ResolverMeta) Reset() {
	*x = ResolverMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolverMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolverMeta) ProtoMessage() {}

func (x *ResolverMeta) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolverMeta.ProtoReflect.Descriptor instead.
func (*ResolverMeta) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{5}
}

func (x *ResolverMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolverMeta) GetBuiltin() bool {
	if x != nil {
		return x.Builtin
	}
	return false
}

type Constraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      ConstraintType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.ConstraintType" json:"type,omitempty"`
	Columns   []string       `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	TableName string         `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{6}
}

func (x *Constraint) GetType() ConstraintType {
	if x != nil {
		return x.Type
	}
	return ConstraintType_PRIMARY_KEY
}

func (x *Constraint) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Constraint) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type GetProviderConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetProviderConfig) Reset() {
	*x = GetProviderConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderConfig) ProtoMessage() {}

func (x *GetProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderConfig.ProtoReflect.Descriptor instead.
func (*GetProviderConfig) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{7}
}

// --------------------------------------------------------------------------------------------------------------------
type CheckConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckConfig) Reset() {
	*x = CheckConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConfig) ProtoMessage() {}

func (x *CheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConfig.ProtoReflect.Descriptor instead.
func (*CheckConfig) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{8}
}

type SetProviderConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetProviderConfig) Reset() {
	*x = SetProviderConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProviderConfig) ProtoMessage() {}

func (x *SetProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProviderConfig.ProtoReflect.Descriptor instead.
func (*SetProviderConfig) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{9}
}

type Storage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type           StorageType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.StorageType" json:"type,omitempty"`
	StorageOptions string      `protobuf:"bytes,2,opt,name=storage_options,json=storageOptions,proto3" json:"storage_options,omitempty"`
}

func (x *Storage) Reset() {
	*x = Storage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{10}
}

func (x *Storage) GetType() StorageType {
	if x != nil {
		return x.Type
	}
	return StorageType_POSTGRESQL
}

func (x *Storage) GetStorageOptions() string {
	if x != nil {
		return x.StorageOptions
	}
	return ""
}

type PullTables struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PullTables) Reset() {
	*x = PullTables{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullTables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullTables) ProtoMessage() {}

func (x *PullTables) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullTables.ProtoReflect.Descriptor instead.
func (*PullTables) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{11}
}

type DropTableAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DropTableAll) Reset() {
	*x = DropTableAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropTableAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTableAll) ProtoMessage() {}

func (x *DropTableAll) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTableAll.ProtoReflect.Descriptor instead.
func (*DropTableAll) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{12}
}

type CreateAllTables struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAllTables) Reset() {
	*x = CreateAllTables{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAllTables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAllTables) ProtoMessage() {}

func (x *CreateAllTables) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAllTables.ProtoReflect.Descriptor instead.
func (*CreateAllTables) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{13}
}

type Diagnostic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiagnosticLevel Diagnostic_DiagnosticLevel `protobuf:"varint,1,opt,name=diagnosticLevel,proto3,enum=proto.Diagnostic_DiagnosticLevel" json:"diagnosticLevel,omitempty"`
	Content         string                     `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{14}
}

func (x *Diagnostic) GetDiagnosticLevel() Diagnostic_DiagnosticLevel {
	if x != nil {
		return x.DiagnosticLevel
	}
	return Diagnostic_DiagnosisLevelTrace
}

func (x *Diagnostic) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ProviderInit_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Storage        *Storage `protobuf:"bytes,1,opt,name=storage,proto3,oneof" json:"storage,omitempty"`
	Workspace      *string  `protobuf:"bytes,2,opt,name=workspace,proto3,oneof" json:"workspace,omitempty"`
	ProviderConfig *string  `protobuf:"bytes,3,opt,name=provider_config,json=providerConfig,proto3,oneof" json:"provider_config,omitempty"`
	IsInstallInit  *bool    `protobuf:"varint,4,opt,name=is_install_init,json=isInstallInit,proto3,oneof" json:"is_install_init,omitempty"`
}

func (x *ProviderInit_Request) Reset() {
	*x = ProviderInit_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderInit_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInit_Request) ProtoMessage() {}

func (x *ProviderInit_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInit_Request.ProtoReflect.Descriptor instead.
func (*ProviderInit_Request) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProviderInit_Request) GetStorage() *Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *ProviderInit_Request) GetWorkspace() string {
	if x != nil && x.Workspace != nil {
		return *x.Workspace
	}
	return ""
}

func (x *ProviderInit_Request) GetProviderConfig() string {
	if x != nil && x.ProviderConfig != nil {
		return *x.ProviderConfig
	}
	return ""
}

func (x *ProviderInit_Request) GetIsInstallInit() bool {
	if x != nil && x.IsInstallInit != nil {
		return *x.IsInstallInit
	}
	return false
}

type ProviderInit_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diagnostics []*Diagnostic `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
}

func (x *ProviderInit_Response) Reset() {
	*x = ProviderInit_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderInit_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInit_Response) ProtoMessage() {}

func (x *ProviderInit_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInit_Response.ProtoReflect.Descriptor instead.
func (*ProviderInit_Response) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ProviderInit_Response) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type GetProviderInformation_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetProviderInformation_Request) Reset() {
	*x = GetProviderInformation_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProviderInformation_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderInformation_Request) ProtoMessage() {}

func (x *GetProviderInformation_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderInformation_Request.ProtoReflect.Descriptor instead.
func (*GetProviderInformation_Request) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{1, 0}
}

type GetProviderInformation_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                  string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version               string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Tables                map[string]*Table `protobuf:"bytes,3,rep,name=tables,proto3" json:"tables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DefaultConfigTemplate string            `protobuf:"bytes,4,opt,name=default_config_template,json=defaultConfigTemplate,proto3" json:"default_config_template,omitempty"`
	Diagnostics           []*Diagnostic     `protobuf:"bytes,5,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
}

func (x *GetProviderInformation_Response) Reset() {
	*x = GetProviderInformation_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProviderInformation_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderInformation_Response) ProtoMessage() {}

func (x *GetProviderInformation_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderInformation_Response.ProtoReflect.Descriptor instead.
func (*GetProviderInformation_Response) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetProviderInformation_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProviderInformation_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetProviderInformation_Response) GetTables() map[string]*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *GetProviderInformation_Response) GetDefaultConfigTemplate() string {
	if x != nil {
		return x.DefaultConfigTemplate
	}
	return ""
}

func (x *GetProviderInformation_Response) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type GetProviderConfig_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetProviderConfig_Request) Reset() {
	*x = GetProviderConfig_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProviderConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderConfig_Request) ProtoMessage() {}

func (x *GetProviderConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderConfig_Request.ProtoReflect.Descriptor instead.
func (*GetProviderConfig_Request) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{7, 0}
}

type GetProviderConfig_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version     string        `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Config      string        `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Diagnostics []*Diagnostic `protobuf:"bytes,4,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
}

func (x *GetProviderConfig_Response) Reset() {
	*x = GetProviderConfig_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProviderConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderConfig_Response) ProtoMessage() {}

func (x *GetProviderConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderConfig_Response.ProtoReflect.Descriptor instead.
func (*GetProviderConfig_Response) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{7, 1}
}

func (x *GetProviderConfig_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProviderConfig_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetProviderConfig_Response) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *GetProviderConfig_Response) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type CheckConfig_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *CheckConfig_Request) Reset() {
	*x = CheckConfig_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConfig_Request) ProtoMessage() {}

func (x *CheckConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConfig_Request.ProtoReflect.Descriptor instead.
func (*CheckConfig_Request) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{8, 0}
}

func (x *CheckConfig_Request) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type CheckConfig_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diagnostics []*Diagnostic `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
}

func (x *CheckConfig_Response) Reset() {
	*x = CheckConfig_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConfig_Response) ProtoMessage() {}

func (x *CheckConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConfig_Response.ProtoReflect.Descriptor instead.
func (*CheckConfig_Response) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{8, 1}
}

func (x *CheckConfig_Response) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type SetProviderConfig_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Storage        *Storage `protobuf:"bytes,1,opt,name=storage,proto3,oneof" json:"storage,omitempty"`
	ProviderConfig *string  `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3,oneof" json:"provider_config,omitempty"`
}

func (x *SetProviderConfig_Request) Reset() {
	*x = SetProviderConfig_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetProviderConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProviderConfig_Request) ProtoMessage() {}

func (x *SetProviderConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProviderConfig_Request.ProtoReflect.Descriptor instead.
func (*SetProviderConfig_Request) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{9, 0}
}

func (x *SetProviderConfig_Request) GetStorage() *Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *SetProviderConfig_Request) GetProviderConfig() string {
	if x != nil && x.ProviderConfig != nil {
		return *x.ProviderConfig
	}
	return ""
}

type SetProviderConfig_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diagnostics []*Diagnostic `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
}

func (x *SetProviderConfig_Response) Reset() {
	*x = SetProviderConfig_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetProviderConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProviderConfig_Response) ProtoMessage() {}

func (x *SetProviderConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProviderConfig_Response.ProtoReflect.Descriptor instead.
func (*SetProviderConfig_Response) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{9, 1}
}

func (x *SetProviderConfig_Response) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type PullTables_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tables        []string `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	MaxGoroutines uint64   `protobuf:"varint,2,opt,name=max_goroutines,json=maxGoroutines,proto3" json:"max_goroutines,omitempty"`
	Timeout       int64    `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *PullTables_Request) Reset() {
	*x = PullTables_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullTables_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullTables_Request) ProtoMessage() {}

func (x *PullTables_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullTables_Request.ProtoReflect.Descriptor instead.
func (*PullTables_Request) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{11, 0}
}

func (x *PullTables_Request) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *PullTables_Request) GetMaxGoroutines() uint64 {
	if x != nil {
		return x.MaxGoroutines
	}
	return 0
}

func (x *PullTables_Request) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type PullTables_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// map of tables that have finished fetching
	FinishedTables map[string]bool `protobuf:"bytes,1,rep,name=finished_tables,json=finishedTables,proto3" json:"finished_tables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// Amount of tables collected so far
	TableCount  uint64        `protobuf:"varint,2,opt,name=table_count,json=tableCount,proto3" json:"table_count,omitempty"`
	Table       string        `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Diagnostics []*Diagnostic `protobuf:"bytes,4,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
}

func (x *PullTables_Response) Reset() {
	*x = PullTables_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullTables_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullTables_Response) ProtoMessage() {}

func (x *PullTables_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullTables_Response.ProtoReflect.Descriptor instead.
func (*PullTables_Response) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{11, 1}
}

func (x *PullTables_Response) GetFinishedTables() map[string]bool {
	if x != nil {
		return x.FinishedTables
	}
	return nil
}

func (x *PullTables_Response) GetTableCount() uint64 {
	if x != nil {
		return x.TableCount
	}
	return 0
}

func (x *PullTables_Response) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *PullTables_Response) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type DropTableAll_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DropTableAll_Request) Reset() {
	*x = DropTableAll_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropTableAll_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTableAll_Request) ProtoMessage() {}

func (x *DropTableAll_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTableAll_Request.ProtoReflect.Descriptor instead.
func (*DropTableAll_Request) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{12, 0}
}

type DropTableAll_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diagnostics []*Diagnostic `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
}

func (x *DropTableAll_Response) Reset() {
	*x = DropTableAll_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropTableAll_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTableAll_Response) ProtoMessage() {}

func (x *DropTableAll_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTableAll_Response.ProtoReflect.Descriptor instead.
func (*DropTableAll_Response) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{12, 1}
}

func (x *DropTableAll_Response) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type CreateAllTables_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAllTables_Request) Reset() {
	*x = CreateAllTables_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAllTables_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAllTables_Request) ProtoMessage() {}

func (x *CreateAllTables_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAllTables_Request.ProtoReflect.Descriptor instead.
func (*CreateAllTables_Request) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{13, 0}
}

type CreateAllTables_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diagnostics []*Diagnostic `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
}

func (x *CreateAllTables_Response) Reset() {
	*x = CreateAllTables_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_internal_provider_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAllTables_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAllTables_Response) ProtoMessage() {}

func (x *CreateAllTables_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_internal_provider_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAllTables_Response.ProtoReflect.Descriptor instead.
func (*CreateAllTables_Response) Descriptor() ([]byte, []int) {
	return file_grpc_internal_provider_proto_rawDescGZIP(), []int{13, 1}
}

func (x *CreateAllTables_Response) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

var File_grpc_internal_provider_proto protoreflect.FileDescriptor

var file_grpc_internal_provider_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x02, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x1a, 0xf8, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x21, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52,
	0x0e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x88,
	0x01, 0x01, 0x12, 0x2b, 0x0a, 0x0f, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x5f, 0x69, 0x6e, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x03, 0x52, 0x0d, 0x69,
	0x73, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x69, 0x74, 0x88, 0x01, 0x01, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x12, 0x0a,
	0x10, 0x5f, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x6e, 0x69,
	0x74, 0x1a, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a,
	0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e,
	0x6f, 0x73, 0x74, 0x69, 0x63, 0x52, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x22, 0xe0, 0x02, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x09, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0xba, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x06, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12,
	0x36, 0x0a, 0x17, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x15, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e,
	0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52,
	0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x1a, 0x47, 0x0a, 0x0b,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xd6, 0x01, 0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27,
	0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x07,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x2b, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x5f, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x09, 0x73, 0x75, 0x62, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x65,
	0x0a, 0x06, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x62, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4d,
	0x65, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x67, 0x6e,
	0x6f, 0x72, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x0c, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x22, 0x70, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xa6, 0x01, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a,
	0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x85, 0x01, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x33, 0x0a,
	0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e,
	0x6f, 0x73, 0x74, 0x69, 0x63, 0x52, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x22, 0x71, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x1a, 0x21, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x1a, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69,
	0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x22, 0xdd, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x86, 0x01, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x42, 0x12, 0x0a, 0x10, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x1a, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69,
	0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x22, 0x5a, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x85, 0x03, 0x0a, 0x0a, 0x50, 0x75, 0x6c, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73,
	0x1a, 0x62, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x67, 0x6f, 0x72, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6d, 0x61, 0x78,
	0x47, 0x6f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x1a, 0x92, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x57, 0x0a, 0x0f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x66, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x12, 0x33, 0x0a, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e,
	0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x1a, 0x41, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5a, 0x0a, 0x0c, 0x44, 0x72, 0x6f,
	0x70, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x6c, 0x6c, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69,
	0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x22, 0x5d, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x6c, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61,
	0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x52, 0x0b, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x22, 0x9b, 0x02, 0x0a, 0x0a, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x74, 0x69, 0x63, 0x12, 0x4b, 0x0a, 0x0f, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69,
	0x63, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x2e,
	0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x0f, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xa5, 0x01, 0x0a, 0x0f, 0x44,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x17,
	0x0a, 0x13, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x54, 0x72, 0x61, 0x63, 0x65, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x69, 0x61, 0x67, 0x6e,
	0x6f, 0x73, 0x69, 0x73, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x10, 0x01,
	0x12, 0x16, 0x0a, 0x12, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x44, 0x69, 0x61, 0x67,
	0x6e, 0x6f, 0x73, 0x69, 0x73, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x57, 0x61, 0x72, 0x6e, 0x10, 0x03,
	0x12, 0x17, 0x0a, 0x13, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x69, 0x61,
	0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x46, 0x61, 0x74, 0x61, 0x6c,
	0x10, 0x05, 0x2a, 0x97, 0x02, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x4d, 0x41, 0x4c,
	0x4c, 0x49, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x54, 0x10, 0x03, 0x12,
	0x0a, 0x0a, 0x06, 0x42, 0x49, 0x47, 0x49, 0x4e, 0x54, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x46,
	0x4c, 0x4f, 0x41, 0x54, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x10, 0x06,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a,
	0x42, 0x59, 0x54, 0x45, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x08, 0x12, 0x10, 0x0a, 0x0c,
	0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x09, 0x12, 0x0d,
	0x0a, 0x09, 0x49, 0x4e, 0x54, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x0a, 0x12, 0x0d, 0x0a,
	0x09, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x54, 0x41, 0x4d, 0x50, 0x10, 0x0b, 0x12, 0x08, 0x0a, 0x04,
	0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x0c, 0x12, 0x0e, 0x0a, 0x0a, 0x55, 0x55, 0x49, 0x44, 0x5f, 0x41,
	0x52, 0x52, 0x41, 0x59, 0x10, 0x0d, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x45, 0x54, 0x10, 0x0e,
	0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x4e, 0x45, 0x54, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x0f,
	0x12, 0x08, 0x0a, 0x04, 0x43, 0x49, 0x44, 0x52, 0x10, 0x10, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x49,
	0x44, 0x52, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x11, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x41,
	0x43, 0x5f, 0x41, 0x44, 0x44, 0x52, 0x10, 0x12, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x41, 0x43, 0x5f,
	0x41, 0x44, 0x44, 0x52, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x13, 0x2a, 0x32, 0x0a, 0x0e,
	0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f,
	0x0a, 0x0b, 0x50, 0x52, 0x49, 0x4d, 0x41, 0x52, 0x59, 0x5f, 0x4b, 0x45, 0x59, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x46, 0x4f, 0x52, 0x45, 0x49, 0x47, 0x4e, 0x5f, 0x4b, 0x45, 0x59, 0x10, 0x01,
	0x2a, 0x28, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0e, 0x0a, 0x0a, 0x50, 0x4f, 0x53, 0x54, 0x47, 0x52, 0x45, 0x53, 0x51, 0x4c, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x4d, 0x59, 0x53, 0x51, 0x4c, 0x10, 0x01, 0x32, 0xd0, 0x04, 0x0a, 0x08, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x04, 0x49, 0x6e, 0x69, 0x74, 0x12,
	0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x49, 0x6e, 0x69, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x69,
	0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a,
	0x11, 0x53, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x50, 0x75, 0x6c, 0x6c, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75,
	0x6c, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x49,
	0x0a, 0x0c, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x6c, 0x6c, 0x12, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x41, 0x6c, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x6c, 0x6c,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a,
	0x09, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_grpc_internal_provider_proto_rawDescOnce sync.Once
	file_grpc_internal_provider_proto_rawDescData = file_grpc_internal_provider_proto_rawDesc
)

func file_grpc_internal_provider_proto_rawDescGZIP() []byte {
	file_grpc_internal_provider_proto_rawDescOnce.Do(func() {
		file_grpc_internal_provider_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_internal_provider_proto_rawDescData)
	})
	return file_grpc_internal_provider_proto_rawDescData
}

var file_grpc_internal_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_grpc_internal_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_grpc_internal_provider_proto_goTypes = []interface{}{
	(ColumnType)(0),                         // 0: proto.ColumnType
	(ConstraintType)(0),                     // 1: proto.ConstraintType
	(StorageType)(0),                        // 2: proto.StorageType
	(Diagnostic_DiagnosticLevel)(0),         // 3: proto.Diagnostic.DiagnosticLevel
	(*ProviderInit)(nil),                    // 4: proto.ProviderInit
	(*GetProviderInformation)(nil),          // 5: proto.GetProviderInformation
	(*Table)(nil),                           // 6: proto.Table
	(*Column)(nil),                          // 7: proto.Column
	(*ColumnMeta)(nil),                      // 8: proto.ColumnMeta
	(*ResolverMeta)(nil),                    // 9: proto.ResolverMeta
	(*Constraint)(nil),                      // 10: proto.Constraint
	(*GetProviderConfig)(nil),               // 11: proto.GetProviderConfig
	(*CheckConfig)(nil),                     // 12: proto.CheckConfig
	(*SetProviderConfig)(nil),               // 13: proto.SetProviderConfig
	(*Storage)(nil),                         // 14: proto.Storage
	(*PullTables)(nil),                      // 15: proto.PullTables
	(*DropTableAll)(nil),                    // 16: proto.DropTableAll
	(*CreateAllTables)(nil),                 // 17: proto.CreateAllTables
	(*Diagnostic)(nil),                      // 18: proto.Diagnostic
	(*ProviderInit_Request)(nil),            // 19: proto.ProviderInit.Request
	(*ProviderInit_Response)(nil),           // 20: proto.ProviderInit.Response
	(*GetProviderInformation_Request)(nil),  // 21: proto.GetProviderInformation.Request
	(*GetProviderInformation_Response)(nil), // 22: proto.GetProviderInformation.Response
	nil,                                     // 23: proto.GetProviderInformation.Response.TablesEntry
	(*GetProviderConfig_Request)(nil),       // 24: proto.GetProviderConfig.Request
	(*GetProviderConfig_Response)(nil),      // 25: proto.GetProviderConfig.Response
	(*CheckConfig_Request)(nil),             // 26: proto.CheckConfig.Request
	(*CheckConfig_Response)(nil),            // 27: proto.CheckConfig.Response
	(*SetProviderConfig_Request)(nil),       // 28: proto.SetProviderConfig.Request
	(*SetProviderConfig_Response)(nil),      // 29: proto.SetProviderConfig.Response
	(*PullTables_Request)(nil),              // 30: proto.PullTables.Request
	(*PullTables_Response)(nil),             // 31: proto.PullTables.Response
	nil,                                     // 32: proto.PullTables.Response.FinishedTablesEntry
	(*DropTableAll_Request)(nil),            // 33: proto.DropTableAll.Request
	(*DropTableAll_Response)(nil),           // 34: proto.DropTableAll.Response
	(*CreateAllTables_Request)(nil),         // 35: proto.CreateAllTables.Request
	(*CreateAllTables_Response)(nil),        // 36: proto.CreateAllTables.Response
}
var file_grpc_internal_provider_proto_depIdxs = []int32{
	7,  // 0: proto.Table.columns:type_name -> proto.Column
	6,  // 1: proto.Table.sub_tables:type_name -> proto.Table
	0,  // 2: proto.Column.type:type_name -> proto.ColumnType
	9,  // 3: proto.ColumnMeta.resolver:type_name -> proto.ResolverMeta
	1,  // 4: proto.Constraint.type:type_name -> proto.ConstraintType
	2,  // 5: proto.Storage.type:type_name -> proto.StorageType
	3,  // 6: proto.Diagnostic.diagnosticLevel:type_name -> proto.Diagnostic.DiagnosticLevel
	14, // 7: proto.ProviderInit.Request.storage:type_name -> proto.Storage
	18, // 8: proto.ProviderInit.Response.diagnostics:type_name -> proto.Diagnostic
	23, // 9: proto.GetProviderInformation.Response.tables:type_name -> proto.GetProviderInformation.Response.TablesEntry
	18, // 10: proto.GetProviderInformation.Response.diagnostics:type_name -> proto.Diagnostic
	6,  // 11: proto.GetProviderInformation.Response.TablesEntry.value:type_name -> proto.Table
	18, // 12: proto.GetProviderConfig.Response.diagnostics:type_name -> proto.Diagnostic
	18, // 13: proto.CheckConfig.Response.diagnostics:type_name -> proto.Diagnostic
	14, // 14: proto.SetProviderConfig.Request.storage:type_name -> proto.Storage
	18, // 15: proto.SetProviderConfig.Response.diagnostics:type_name -> proto.Diagnostic
	32, // 16: proto.PullTables.Response.finished_tables:type_name -> proto.PullTables.Response.FinishedTablesEntry
	18, // 17: proto.PullTables.Response.diagnostics:type_name -> proto.Diagnostic
	18, // 18: proto.DropTableAll.Response.diagnostics:type_name -> proto.Diagnostic
	18, // 19: proto.CreateAllTables.Response.diagnostics:type_name -> proto.Diagnostic
	19, // 20: proto.Provider.Init:input_type -> proto.ProviderInit.Request
	21, // 21: proto.Provider.GetProviderInformation:input_type -> proto.GetProviderInformation.Request
	24, // 22: proto.Provider.GetProviderConfig:input_type -> proto.GetProviderConfig.Request
	28, // 23: proto.Provider.SetProviderConfig:input_type -> proto.SetProviderConfig.Request
	30, // 24: proto.Provider.PullTables:input_type -> proto.PullTables.Request
	33, // 25: proto.Provider.DropTableAll:input_type -> proto.DropTableAll.Request
	35, // 26: proto.Provider.CreateAllTables:input_type -> proto.CreateAllTables.Request
	20, // 27: proto.Provider.Init:output_type -> proto.ProviderInit.Response
	22, // 28: proto.Provider.GetProviderInformation:output_type -> proto.GetProviderInformation.Response
	25, // 29: proto.Provider.GetProviderConfig:output_type -> proto.GetProviderConfig.Response
	29, // 30: proto.Provider.SetProviderConfig:output_type -> proto.SetProviderConfig.Response
	31, // 31: proto.Provider.PullTables:output_type -> proto.PullTables.Response
	34, // 32: proto.Provider.DropTableAll:output_type -> proto.DropTableAll.Response
	36, // 33: proto.Provider.CreateAllTables:output_type -> proto.CreateAllTables.Response
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_grpc_internal_provider_proto_init() }
func file_grpc_internal_provider_proto_init() {
	if File_grpc_internal_provider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_internal_provider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProviderInformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Table); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Column); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolverMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Constraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProviderConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetProviderConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Storage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullTables); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropTableAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAllTables); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diagnostic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderInit_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderInit_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProviderInformation_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProviderInformation_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProviderConfig_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProviderConfig_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckConfig_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckConfig_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetProviderConfig_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetProviderConfig_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullTables_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullTables_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropTableAll_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropTableAll_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAllTables_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_internal_provider_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAllTables_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpc_internal_provider_proto_msgTypes[15].OneofWrappers = []interface{}{}
	file_grpc_internal_provider_proto_msgTypes[24].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_internal_provider_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_internal_provider_proto_goTypes,
		DependencyIndexes: file_grpc_internal_provider_proto_depIdxs,
		EnumInfos:         file_grpc_internal_provider_proto_enumTypes,
		MessageInfos:      file_grpc_internal_provider_proto_msgTypes,
	}.Build()
	File_grpc_internal_provider_proto = out.File
	file_grpc_internal_provider_proto_rawDesc = nil
	file_grpc_internal_provider_proto_goTypes = nil
	file_grpc_internal_provider_proto_depIdxs = nil
}
